### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vmarcosp** [rescriptbr/ancestor#4]
## Description
We need to create documentation for the library. Since we're using ReScript it will be greater if we have a simple way to create documentation about the library's components, props, functions, and types.

## Tasks
- [x] Translate from pt-br to en-us
- [x] "What and Why?" section 
- [x] Installation section
- [x] Getting started section 
- [x] Documentation of all responsive props
- [x] Examples section
- [x] Documentation of all components and props
- [x] Documentation of all functions and types

## System props
- [x] borderRadius
- [x] border
- [x] borderRight
- [x] borderLeft
- [x] borderTop
- [x] borderBottom
- [x] bgColor
- [x] color
- [x] display
- [x] justifyContent
- [x] flexDirection
- [x] alignItems
- [x] flexBasis
- [x] flexWrap
- [x] flexGrow
- [x] alignContent
- [x] alignSelf
- [x] justifySelf
- [x] flexFlow
- [x] p
- [x] px
- [x] py
- [x] pt
- [x] pb
- [x] pl
- [x] pr
- [x] m
- [x] mx
- [x] my
- [x] mt
- [x] mb
- [x] ml
- [x] mr
- [x] textAlign
- [x] fontWeight
- [x] fontSize
- [x] letterSpacing
- [x] lineHeight
- [x] width
- [x] height
- [x] minW
- [x] minH
- [x] maxW
- [x] maxH
- [x] position
- [x] top
- [x] bottom
- [x] left
- [x] right
- [x] zIndex
- [x] boxSizing
